sciurus17_controlのROS 2対応
rt-net/sciurus17_ros pull request #142
Opened 2023-11-01 09:02 UTC by Kuwamai

# What does this implement/fix?

- sciurus17_controlのROS 2対応です。
- 実機のSciurus17がMoveItを用いて動くようになります。
- 下記PRに依存しているためpullしてから動作確認お願いします。
  - https://github.com/rt-net/sciurus17_description/pull/7

# Does this close any currently open issues?

しません

# How has this been tested?

下記コマンドを実行し、RVizから実機のアームを操作できることを確認しました。

```
ros2 launch sciurus17_examples demo.launch.py
```

# Any other comments?

ありません

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-11-02 09:19 UTC, ShotaAk requested changes
確認しました。動作OKです。

コメントの確認お願いします

2023-11-02 09:19 UTC, ShotaAk commented on sciurus17_control/src/sciurus17_hardware.cpp
> +      // 発生頻度が低い場合は問題ないためOKを返す
OKを返す理由を明確にしたいです。
```suggestion
      // sync_readに失敗しても通信は継続させる。
      // 不確かなデータをセットしないようにOKを返す。
```

2023-11-02 10:02 UTC, Kuwamai commented on sciurus17_control/src/sciurus17_hardware.cpp
> +    double limit_max = present_position;
limit_min、limit_maxは値が変更されるのでconstは使えませんでした。

2023-11-02 10:07 UTC, Kuwamai commented on sciurus17_control/src/sciurus17_hardware.cpp
> +  for (auto joint : info_.joints) {
joint.parametersがconstにオーバーロードできないためこの変更はできませんでした。

2023-11-06 00:52 UTC, ShotaAk commented on sciurus17_control/src/sciurus17_hardware.cpp
> +  for (auto joint : info_.joints) {
[ ]ではなくat( )を使ってみてください。

2023-11-06 04:09 UTC, ShotaAk approved these changes
LGTMです。

2023-11-06 04:09 UTC, merged