カメラトラッキングサンプル追加
rt-net/sciurus17_ros pull request #151
Opened 2023-11-21 09:43 UTC by Kuwamai

# What does this implement/fix?

# Does this close any currently open issues?

# How has this been tested?

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-11-22 05:36 UTC, ShotaAk requested changes
動作OKです。コメントの確認お願いします。

2023-11-22 05:36 UTC, ShotaAk commented on sciurus17_examples/launch/demo.launch.py
カメラ・点群トピックのQoSをSensorDataプロファイルに合わせたいです。
https://github.com/ros2/rmw/blob/rolling/rmw/include/rmw/qos_profiles.h

Reliability をBest Effortにしてください

![image](https://github.com/rt-net/sciurus17_ros/assets/18494952/00214c90-8d25-4fb4-8db2-ba9ff472f016)

2023-11-22 05:36 UTC, ShotaAk commented on sciurus17_vision/config/camera_info.yaml
![image](https://github.com/rt-net/sciurus17_ros/assets/18494952/9c3ba509-28ee-4be2-9d48-c8b023aebc8f)

旧カメラではズレが発生してますが、現行モデルでは一致してますかね？

2023-11-22 05:36 UTC, ShotaAk commented on sciurus17_vision/config/camera_info.yaml
> +camera_name: narrow_stereo
stereoカメラでは無いと思います。

2023-11-22 05:36 UTC, ShotaAk commented on sciurus17_vision/config/camera_info.yaml
> +  data: [-0.221837, 1.448854, -1.560465, 0.357714]
これらはキャリブレーション済みのパラメータですか？

その場合、sciurus17_visionのキャリブレーション済みであることをREADMEに記載お願いします。

2023-11-22 05:36 UTC, ShotaAk commented on sciurus17_vision/launch/chest_camera.launch.py
> +                {'framerate': 30.0},
参考情報：
私の環境ではimage_rawが16 Hz、/chest_camera/image_raw/compressedが30Hzでした。

2023-11-24 06:11 UTC, Kuwamai commented on sciurus17_examples/launch/demo.launch.py
後ろから見た画角にしてしまうとアームの操作やS17の姿勢の確認といった、点群の可視化より使用頻度の多い機能に支障があると思うので画角は変えるべきではないと思います。
またbox_stackingのような点群を用いたサンプルではS17は下を向くため、S17の正面からの画角がいいと思います。
いかがでしょうか。

2023-11-24 08:06 UTC, Kuwamai commented on sciurus17_vision/config/camera_info.yaml
次回以降のPRで修正します

2023-11-24 08:21 UTC, ShotaAk commented on sciurus17_examples/launch/demo.launch.py
了解しました。ではこのままで進めましょう。

2023-11-24 08:23 UTC, ShotaAk approved these changes
LGTM

2023-11-24 08:23 UTC, merged