頭部カメラサンプル追加
rt-net/sciurus17_ros pull request #153
Opened 2023-12-13 06:00 UTC by Kuwamai

# What does this implement/fix?

頭部カメラを用いた物体追従サンプルを追加します。

# Does this close any currently open issues?

しません

# How has this been tested?

Sciurus17とRealSenseをPCに接続し、下記コマンドで起動します。

```
ros2 launch sciurus17_examples demo.launch.py
ros2 launch sciurus17_examples object_tracking.launch.py
```

# Any other comments?

なし

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-12-25 10:13 UTC, ShotaAk commented
usb_camパッケージの変更により`/dev/video*/`以外のデバイス名を認識できなくなりました。

下記のように　chest_camera.launch.py の変更をお願いします。

```python
            parameters=[
                {'video_device': os.path.realpath('/dev/chestcamera')},
```

https://github.com/ros-drivers/usb_cam/issues/298

2023-12-25 11:37 UTC, ShotaAk requested changes
胸カメラサンプルを動かしました。コメントの確認お願いします。

2023-12-25 11:37 UTC, ShotaAk commented on sciurus17_examples/src/color_detection.cpp
> +  if (d_area > 100000) {
ここのしきい値は小さいと思います。

下記のような写り方でも400000程度の値になるので、しきい値を大きくしてください。

カメラ画像のwidth、heightから求めたしきい値を作れば、カメラ解像度に依存しない判定が作れそうです。

![image](https://github.com/rt-net/sciurus17_ros/assets/18494952/3dd49ffc-1038-4ea4-adcc-e6bf845e169f)

2023-12-25 11:37 UTC, ShotaAk commented on sciurus17_examples/CMakeLists.txt
> +set(node_plgins "${node_plugins}sciurus17_examples::ColorDetection;$<TARGET_FILE:color_detection>\n")
node_plugins変数は使われていないので削除してください。
流用元でもテストにしか使用されてないので不要です。

2023-12-25 11:37 UTC, ShotaAk commented on sciurus17_examples/package.xml
> +  <depend>pcl_ros</depend>
```suggestion
```
このPRではpcl未使用なので削除お願いします。

2023-12-25 11:37 UTC, ShotaAk commented on sciurus17_examples/package.xml
> +  <depend>realsense2_camera</depend>
```suggestion
```
このPRではrealsense2に依存したコードを書いてないので削除お願いします。

2023-12-25 11:37 UTC, ShotaAk commented on sciurus17_examples/src/color_detection.cpp
> +    "/head_camera/color/image_raw", 10, std::bind(&ColorDetection::image_callback, this, _1));
頭カメラ、胸カメラ両方に対応しているとわかるように、抽象的なトピック名にしてください。

2023-12-25 11:37 UTC, ShotaAk commented on sciurus17_examples/src/color_detection.cpp
> +  // 周囲の明るさ等の動作環境に合わせて調整
2行目のコメントは書きかけですかね？　削除して良いと思います。

2023-12-25 11:37 UTC, ShotaAk commented on sciurus17_examples/src/color_detection.cpp
> +  // ウェブカメラの画像を受け取る
ここでは受け取っていないので正しいコメントではないです。
コメント削除でもOKです

2023-12-25 11:37 UTC, ShotaAk commented on sciurus17_examples/src/object_tracker.cpp
> +    "/neck_controller/controller_state", 10, std::bind(&ObjectTracker::state_callback, this, _1));
腰軸にも対応しているとわかるように、抽象的な名前に変えてください。

2023-12-25 11:37 UTC, ShotaAk commented on sciurus17_examples/src/object_tracker.cpp
> +  }
1と2だとわかりにくいので、
NECK_JOINTS_NUM、WAIST_JOINT_NUMのような定数にしてください

2023-12-26 07:28 UTC, Kuwamai commented on sciurus17_examples/src/color_detection.cpp
> +  // 周囲の明るさ等の動作環境に合わせて調整
書きかけではなくCRANE-X7、CRANE+ V2と共通のコメントになっています。ただし「調整」の主体が不明確な表現となっているため削除します。

2024-02-21 02:19 UTC, ShotaAk approved these changes

2024-02-21 02:22 UTC, merged