ROS 2 Jazzyに対応します
rt-net/sciurus17_ros pull request #158
Opened 2024-07-18 00:31 UTC by chama1176

# What does this implement/fix?

ROS 2 Jazzyに対応します

# Does this close any currently open issues?

No.

# How has this been tested?

実機とシミュレーションでExamplesが動作することを確認しています

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-11-12 12:04 UTC, Kuwamai requested changes
@chama1176
PRありがとうございます。
実機ですべてのサンプルの動作確認ができました。

Gazeboが起動しなかったため、シミュレータの動作は未確認です。
コメントをご確認お願いします。

2024-11-12 12:04 UTC, Kuwamai commented on README.md
> +git clone -b feature/support-jazzy https://github.com/rt-net/rt_manipulators_cpp.git
こちらマージ後のブランチ名でお願いします。
```suggestion
git clone -b ros2 https://github.com/rt-net/rt_manipulators_cpp.git
```

2024-11-12 12:04 UTC, Kuwamai commented on sciurus17_moveit_config/launch/run_move_group.launch.py
> +        .trajectory_execution(file_path="config/moveit_controllers.yaml")
kinematics.yaml等と同様に、`moveit_controllers.yaml`は`MoveItConfigsBuilder`のデフォルトパスに設定されているのでこの行はなくてもよさそうです。
```suggestion
```

2024-11-12 12:04 UTC, Kuwamai commented on README.md
> +git clone -b 5.1.4 https://github.com/ros-perception/image_common.git
5.1.4のリリースが完了しており、動作確認ができたためこちらの記述も削除でお願いします。
```suggestion
```

2024-11-12 12:04 UTC, Kuwamai commented on README.md
> +そのためsciurus17関連のパッケージと合わせてソースからビルドします
5.1.4のリリースが完了しており、動作確認ができたためこちらの記述も削除でお願いします。
```suggestion
```

2024-11-12 12:04 UTC, Kuwamai commented on README.md
> +git clone -b 5.1.4 https://github.com/ros-perception/image_common.git
pcl_rosのパッケージ依存関係の変更に伴って点群検出サンプルのビルドが失敗するようになりました。
```
  Could not find a package configuration file provided by "PCL" with any of
  the following names:

    PCLConfig.cmake
    pcl-config.cmake
```

とりあえずlibpcl-devを手動でインストールすることでサンプルのビルドと動作確認ができたので、問題なければこちらの手順を追記お願いしたいです。

```
sudo apt install libpcl-dev
```

こちらで議論されている変更が適用されることで解決しそうです。
https://github.com/ros-perception/perception_pcl/pull/447

2024-11-12 12:04 UTC, Kuwamai commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
Gazeboシミュレータが起動中に落ちました。
@chama1176 さんの環境では正常に起動しましたでしょうか?

2024-11-12 12:04 UTC, Kuwamai commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
こちらの環境だとGUIまわりでエラーが起きていているようです。
```
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1301] [0m[1;31m Unable to create the rendering window: [0m[1;31mOGRE EXCEPTION(3:RenderingAPIException): currentGLContext was specified with no current GL context in GLXWindow::create at ./.obj-x86_64-linux-gnu/gz_ogre_next_vendor-prefix/src/gz_ogre_next_vendor/RenderSystems/GL3Plus/src/windowing/GLX/OgreGLXWindow.cpp (line 165)[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1309] [0m[1;31mUnable to create the rendering window after [[0m[1;31m11[0m[1;31m] attempts.[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1191] [0m[1;31mFailed to create dummy render window.[0m[1;31m[0m
[gz sim -r-1] [1;31m[GUI] [Err] [Ogre2RenderEngine.cc:1192] [0m[1;31mPlease see the troubleshooting page for possible fixes: [0m[1;31mhttps://gazebosim.org/docs/fortress/troubleshooting[0m[1;31m[0m
```

WaylandでなくXorgに切り替えると上記エラーは表示されなくなりましたが、limitsとmimic jointまわりでエラーが出ています。
```
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-2.8797932657906435"' and max: '2.8797932657906435"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '0.9599310885968813"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '1.5707963267948966"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.6057029118347832"' and max: '0.0"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '1.5707963267948966"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-0.00017453292519943296"' and max: '2.7401669256310974"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '1.5707963267948966"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-2.1467549799530254"' and max: '1.0471975511965976"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-2.9670597283903604"' and max: '2.9670597283903604"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-0.0008726646259971648"' and max: '1.5009831567151235"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] terminate called after throwing an instance of 'std::runtime_error'
[gz sim -r-1]   what():  Joint 'r_gripper_mimic_joint' has mimic attribute not set to false: Activated mimic joints cannot have command interfaces.
[gz sim -r-1] Stack trace (most recent call last) in thread 13484:
[gz sim -r-1] #18   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
[gz sim -r-1] #17   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7184bd129c3b, in 
[gz sim -r-1] #16   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7184bd09ca93, in 
[gz sim -r-1] #15   Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7184b7eecdb3, in 
[gz sim -r-1] #14   Object "/opt/ros/jazzy/lib/librclcpp.so", at 0x718480918df6, in rclcpp::executors::MultiThreadedExecutor::run(unsigned long)
[gz sim -r-1] #13   Object "/opt/ros/jazzy/lib/librclcpp.so", at 0x718480907bf9, in rclcpp::Executor::execute_any_executable(rclcpp::AnyExecutable&)
[gz sim -r-1] #12   Object "/opt/ros/jazzy/lib/librclcpp.so", at 0x7184809074ca, in rclcpp::Executor::execute_subscription(std::shared_ptr<rclcpp::SubscriptionBase>)
[gz sim -r-1] #11   Object "/opt/ros/jazzy/lib/libcontroller_manager.so", at 0x7184a4dafda4, in 
[gz sim -r-1] #10   Object "/opt/ros/jazzy/lib/libcontroller_manager.so", at 0x7184a4d3f17a, in controller_manager::ControllerManager::robot_description_callback(std_msgs::msg::String_<std::allocator [...]

2024-11-13 02:11 UTC, chama1176 commented on sciurus17_moveit_config/launch/run_move_group.launch.py
> +        .trajectory_execution(file_path="config/moveit_controllers.yaml")
ありがとうございます。適応します

2024-11-13 02:14 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
PR作成時は私の方では動作確認できていました。
変更入っている可能性もあるので再度確認してみます

2024-11-13 07:12 UTC, chama1176 commented on README.md
> +git clone -b 5.1.4 https://github.com/ros-perception/image_common.git
READMEに追記します

2024-11-13 07:20 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
私の環境でも落ちる現象が再現しました
確認します

2024-11-13 07:31 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
PR作成時（おそらくv8.5.0）からv8.6.0になって差分が大きそうなので、今のバージョンで動くように修正します

2024-11-13 08:09 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
https://github.com/rt-net/sciurus17_description/pull/14/commits/0d3e34a53e5292369f8486ae859bfff37e135f9a
こちらのコミットで修正しました

2024-11-13 08:17 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
GUIはX11でのみ確認しています

2024-11-15 11:11 UTC, Kuwamai commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
ありがとうございます。
Gazeboが起動し、サンプルコードが動作することを確認しました。

自分の環境では下記エラーが引き続き出ているのでちょっと環境に問題がないか確認したいと思います。
```
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-2.8797932657906435"' and max: '2.8797932657906435"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '0.9599310885968813"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '1.5707963267948966"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.6057029118347832"' and max: '0.0"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '1.5707963267948966"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-0.00017453292519943296"' and max: '2.7401669256310974"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '1.5707963267948966"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-2.1467549799530254"' and max: '1.0471975511965976"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-2.9670597283903604"' and max: '2.9670597283903604"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-0.0008726646259971648"' and max: '1.5009831567151235"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '1.5707963267948966"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '0.0"' and max: '1.6057029118347832"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '1.5707963267948966"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-2.7401669256310974"' and max: '0.00017453292519943296"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5707963267948966"' and max: '1.5707963267948966"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.0471975511965976"' and max: '2.1467549799530254"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-2.9670597283903604"' and max: '2.9670597283903604"'] within ros2_control tag inside the URDF. Skipping it
[gz sim -r-1] Error parsing the limits for the interface: position from the tags [min: '-1.5009831567151235"' and max: '0.0008726646259971648"'] within ros2_control tag inside the URDF. Skipping it
```

2024-11-15 11:30 UTC, Kuwamai commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
気になるエラーや警告があったので来週確認したいと思います。
一旦こちらにも記録として残します。

物理エンジンにmimic contraintsがないエラー
```
[gz sim -r-1] [1;31m[Err] [Physics.cc:1772] [0m[1;31mAttempting to create a mimic constraint for joint [[0m[1;31ml_gripper_mimic_joint[0m[1;31m] but the chosen physics engine does not support [0m[1;31mmimic constraints, so no constraint will be [0m[1;31mcreated.[0m[1;31m[0m
```
gz_frame_idが廃止されているかもしれない

```
[gz sim -r-1] [1;33mWarning [Utils.cc:132][0m [/sdf/model[@name="sciurus17"]/link[@name="body_link"]/sensor[@name="chest_camera"]/gz_frame_id:<urdf-string>:L0]: XML Element[gz_frame_id], child of element[sensor], not defined in SDF. Copying[gz_frame_id] as children of [sensor].
[gz sim -r-1] [1;33mWarning [Utils.cc:132][0m [/sdf/model[@name="sciurus17"]/link[@name="neck_pitch_link"]/sensor[@name="sim_realsense_d415"]/gz_frame_id:<urdf-string>:L0]: XML Element[gz_frame_id], child of element[sensor], not defined in SDF. Copying[gz_frame_id] as children of [sensor].
```
GripperActionControllerに変更がある

```
[gz sim -r-1] [WARN] [1731668600.783905740] [left_gripper_controller]: [Deprecated]: the `position_controllers/GripperActionController` and `effort_controllers::GripperActionController` controllers are replaced by 'parallel_gripper_controllers/GripperActionController' controller
```

2024-11-18 02:14 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
> 自分の環境では下記エラーが引き続き出ているのでちょっと環境に問題がないか確認したいと思います。

すみません、再確認すると私の環境でも出ていました

2024-11-19 02:58 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
`Error parsing the limits for the interface`のエラーですが、タイポをros2 controlの方だけ修正して、gazebo_ros2_controlの方を修正していなかったのが要因でした
https://github.com/rt-net/sciurus17_description/pull/14/commits/981c47bd08c78db4bb53318d3d298fdcdfad5674
で修正しました

今までもエラー出ていたのではというような要因ですね

2024-11-19 03:08 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
物理エンジンにmimic contraintsがないエラー
は公式でも認識されているようです。
https://github.com/ros-controls/gz_ros2_control/issues/340
DART使う場合は無視してとのことのようです。bulletに変更することで回避できるようです

2024-11-19 04:57 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
> gz_frame_idが廃止されているかもしれない
に関してですが、下記の通り、SDF側に定義されていないだけのようなので、問題はなさそうです。
https://github.com/gazebosim/gz-sensors/issues/306

探している中で見つけましたが、今後はgz_frame_id等は廃止になってframe_idに統一されるようです。
https://github.com/gazebosim/sdformat/pull/1454
ただしsdformat15からの変更のようなので、sdformat14を使っている現在のgz-sim8.x.xではframe_idで設定してもワーニングが出ます。

こちらのコミットでframe_idに変更しました
https://github.com/rt-net/sciurus17_description/pull/14/commits/0bb38998571940144eaaea8b63945d0181cc3f4b

2024-11-19 05:09 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
GripperActionControllerの廃止に関してはmsg型なども変わり変更量がさすがに多いので、
調査して別PRで対応検討とさせていただきたいです
https://github.com/ros-controls/ros2_controllers/pull/1002

ちょうどこのPRを作成したあたりのタイミングでmainにmergeされた新機能のようです

こちらにIssue起案しました
https://github.com/rt-net/sciurus17_ros/issues/163

2024-11-19 05:09 UTC, chama1176 commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
@Kuwamai 
記載いただいた事項に関して状況確認と修正行いましたので、改めて確認いただけると幸いです

2024-11-20 08:12 UTC, Kuwamai commented on sciurus17_gazebo/launch/sciurus17_with_table.launch.py
@chama1176 
ご確認ありがとうございます！
エラーが出ていないことを確認しました。
先にdescriptionパッケージのほうApproveします

2024-11-21 06:11 UTC, chama1176 commented
@Kuwamai 
CI通るように修正したので再度確認お願いします

依存関係追加以外にフォーマット修正も行いました

2024-11-21 10:27 UTC, Kuwamai approved these changes
@chama1176
確認しました。LGTMです。

2024-11-21 10:27 UTC, merged