moveit_pyでロボットを動かすサンプルを追加します
rt-net/sciurus17_ros pull request #164
Opened 2024-11-28 02:22 UTC by chama1176

# What does this implement/fix?

moveit_pyでロボットを動かすサンプルを追加します

# Does this close any currently open issues?

# How has this been tested?

mock componentsを用いてCppサンプルと同様に動くことを確認

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-12-17 02:19 UTC, Kuwamai requested changes
@chama1176 
PRありがとうございます。
いくつかコメントしたのでご確認お願いします。

また、READMEのパッケージ一覧部分にsciurus17_examples_pyの記述を追加お願いします。
https://github.com/rt-net/sciurus17_ros/tree/ros2?tab=readme-ov-file#packages

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/README.md
> +# sciurus17_examples
細かいですがせっかくなので`_py`付けておくといいと思います。
```suggestion
# sciurus17_examples_py
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/README.md
> +- [sciurus17\_examples](#sciurus17_examples)
```suggestion
- [sciurus17\_examples\_py](#sciurus17_examples_py)
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/README.md
> +Mock Componentsではカメラを使ったサンプルを実行することはできません。
起動方法は一箇所にまとめておきたいので、`sciurus17_examples`のREADMEを案内する形にしていただきたいです。
Python版で手順が異なる場合はそれぞれ書く必要があると思いますが見たところなさそうでしょうか。
↓こんな感じで書いていただければいいかなと思ってます。

```
## 起動方法
Sciurus17の起動方法はsciurus17_examplesのREADMEを参照してください。
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/launch/example.launch.py
> +                        in sciurus17_description.'))
個々にadd_actionする形式になっていますが、とくに理由がなければsciurus17_examplesと同じように最後にLaunchDescriptionのリストを作成するようにしていただくと統一感があるかと思います。
https://github.com/rt-net/sciurus17_ros/blob/feature/moveit_py/sciurus17_examples/launch/example.launch.py#L79-L84

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/launch/example.launch.py
> +            '/config/sciurus17_moveit_py_examples.yaml').to_moveit_configs())
こちらもsciurus17_examplesと同じように`.`ごとに改行すると読みやすいかと思います。
また、trajectory_executionやplanning_pipelinesは記述不要かと思いますのでご確認お願いします。
https://github.com/rt-net/sciurus17_ros/blob/feature/moveit_py/sciurus17_moveit_config/launch/run_move_group.launch.py#L37-L45

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/gripper_control.py
> +    # Finishe with error. Related Issue
こちらは誤字でしょうか
```suggestion
    # Finish with error. Related Issue
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/neck_control.py
> +    # Finishe with error. Related Issue
```suggestion
    # Finish with error. Related Issue
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/gripper_control.py
> +    robot_model = sciurus17.get_robot_model()
`robot_state`の作成はプランニングごとでなく、このタイミングでいいかと思います。

```suggestion
    robot_model = sciurus17.get_robot_model()
    robot_state = RobotState(robot_model)
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/neck_control.py
> +
C++と同様にどの角度が上下左右どちらを向いているのかコメントを書いていただくとわかりやすいかと思います。
`// 首を左に向ける、右、前、上、下、// "neck_init_pose"に戻す`

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_right_arm_waist.py
> +    # Finishe with error. Related Issue
```suggestion
    # Finish with error. Related Issue
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/waist_control.py
> +    # Finishe with error. Related Issue
```suggestion
    # Finish with error. Related Issue
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_left_arm.py
> +    # Finishe with error. Related Issue
```suggestion
    # Finish with error. Related Issue
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/gripper_control.py
> +    robot_model = sciurus17.get_robot_model()
これで問題なさそうでしたら他のサンプルにも反映していただきたいです。

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/waist_control.py
> +
こちらも左、右のコメントを追加お願いします。  
// 腰を左に向ける

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_left_arm.py
> +    PRE_AND_POST_GRASP_POSE.position.z += LIFTING_HEIFHT
名称がややこしいのですがこちらは加算する値でなく高さの値そのものとなっています。
そのため下記の実装でお願いします。
```suggestion
    PRE_AND_POST_GRASP_POSE.position.z = LIFTING_HEIFHT
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_left_arm.py
> +    PRE_AND_POST_RELEASE_POSE.position.z += LIFTING_HEIFHT
```suggestion
    PRE_AND_POST_RELEASE_POSE.position.z = LIFTING_HEIFHT
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_right_arm_waist.py
> +    PRE_AND_POST_GRASP_POSE.position.z += LIFTING_HEIFHT
```suggestion
    PRE_AND_POST_GRASP_POSE.position.z = LIFTING_HEIFHT
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_right_arm_waist.py
> +    PRE_AND_POST_RELEASE_POSE.position.z += LIFTING_HEIFHT
```suggestion
    PRE_AND_POST_RELEASE_POSE.position.z = LIFTING_HEIFHT
```

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_left_arm.py
> +                         pose_link='l_link7')
細かいですが、インデントが長くて見づらいように思いました。
63行目のそれぞれのposeを定義する時点でPoseStampedを作成するのはいかがでしょうか。

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_left_arm.py
> +                         pose_link='l_link7')
もしくはmoveit_py公式サンプルのように実行するたびにgoal_poseを作成するのもよいかと思います。

2024-12-17 02:19 UTC, Kuwamai commented on sciurus17_examples_py/launch/example.launch.py
> +
use_sim_timeオプションがないためGazeboで動作することができませんでした。
ご確認お願いします。

とりあえずこちらの変更で動作することは確認できました。
https://github.com/moveit/moveit2/issues/2940#issuecomment-2401302214

こちらも関連するIssueかと思いますのでご参考ください。
https://github.com/moveit/moveit2/issues/2219

2024-12-17 03:05 UTC, chama1176 commented on sciurus17_examples_py/sciurus17_examples_py/gripper_control.py
> +    # Finishe with error. Related Issue
ありがとうございます修正します

2024-12-17 03:07 UTC, chama1176 commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_left_arm.py
> +    PRE_AND_POST_RELEASE_POSE.position.z += LIFTING_HEIFHT
これは`+=`であっている気がしますが、どういった指摘でしょうか

2024-12-17 03:11 UTC, chama1176 commented on sciurus17_examples_py/launch/example.launch.py
> +
実行時にこちらのオプションは付けられてますか？
https://github.com/rt-net/sciurus17_ros/tree/feature/moveit_py/sciurus17_examples_py#gazebo%E3%81%A7%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88

2024-12-17 04:28 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_left_arm.py
> +    PRE_AND_POST_RELEASE_POSE.position.z += LIFTING_HEIFHT
すみませんコメントをこちらにのみ付けておりました。
C++サンプルでは`PRE_AND_POST_RELEASE_POSE.position.z`の値は0.12+0.25した0.37でなく、0.25となっております。
https://github.com/rt-net/sciurus17_ros/pull/164#discussion_r1886686205

加算しても動作に支障はないのですが、C++サンプルでは加算していないためサンプル間で挙動が異なる状態になってしまいます。できれば揃えていただくと良いかと思います。

2024-12-17 04:33 UTC, Kuwamai commented on sciurus17_examples_py/launch/example.launch.py
> +
オプションを付けて実行しましたが下記エラーが出力され動作しませんでした。
launchファイル内にuse_sim_timeに関する記述がないと実行時のオプションが反映されない認識なのですが合っておりますでしょうか。
たとえばsciurus17_examplesのlaunchファイルでは下記のように記述しています。
https://github.com/rt-net/sciurus17_ros/blob/ros2/sciurus17_examples/launch/example.launch.py#L66-L69
https://github.com/rt-net/sciurus17_ros/blob/ros2/sciurus17_examples/launch/example.launch.py#L80-L81

```
[gripper_control-1] [INFO] [1734351408.225859696] [moveit_3717691570.moveit.ros.current_state_monitor]: Didn't receive robot state (joint angles) with recent timestamp within 10.000000 seconds. Requested time 1734351398.225767, but latest received state has time 11.740000.
[gripper_control-1] Check clock synchronization if your are running ROS across multiple machines!
[gripper_control-1] [FATAL] [1734351408.225957538] [moveit_3717691570.moveit.ros.moveit_cpp]: Unable to configure planning scene monitor
[gripper_control-1] [INFO] [1734351408.248667411] [moveit_3717691570.moveit.ros.planning_scene_monitor]: Stopped publishing maintained planning scene.
[gripper_control-1] [INFO] [1734351408.248716378] [moveit_3717691570.moveit.ros.planning_scene_monitor]: Stopping world geometry monitor
[gripper_control-1] [INFO] [1734351408.248720420] [moveit_3717691570.moveit.ros.planning_scene_monitor]: Stopping planning scene monitor
[gripper_control-1] Traceback (most recent call last):
[gripper_control-1]   File "/home/rt-user/ros2_ws/install/sciurus17_examples_py/lib/sciurus17_examples_py/gripper_control", line 33, in <module>
[gripper_control-1]     sys.exit(load_entry_point('sciurus17-examples-py', 'console_scripts', 'gripper_control')())
[gripper_control-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[gripper_control-1]   File "/home/rt-user/ros2_ws/build/sciurus17_examples_py/sciurus17_examples_py/gripper_control.py", line 35, in main
[gripper_control-1]     sciurus17 = MoveItPy(node_name='gripper_control')
[gripper_control-1]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[gripper_control-1] RuntimeError: Unable to configure planning scene monitor
```

2024-12-17 04:54 UTC, chama1176 commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_left_arm.py
> +    PRE_AND_POST_RELEASE_POSE.position.z += LIFTING_HEIFHT
なるほど。了解です。適応します

2024-12-17 04:58 UTC, chama1176 commented on sciurus17_examples_py/launch/example.launch.py
> +
ありがとうございます。
確かにmoveit_pyの方抜けてますね、修正します

2024-12-17 05:13 UTC, chama1176 commented on sciurus17_examples_py/sciurus17_examples_py/gripper_control.py
> +    robot_model = sciurus17.get_robot_model()
そうですね。最初に持ってきても悪影響はないのですが、前半で書き換えたrobot_stateを後半でもそのまま使いまわすことになり、指定する場所以外のところにも値が入るのが少し気持ち悪いかなと思い、各位置に置いていましたが、どうでしょうか

2024-12-17 05:14 UTC, chama1176 commented on sciurus17_examples_py/sciurus17_examples_py/pick_and_place_left_arm.py
> +                         pose_link='l_link7')
修正します

2024-12-17 05:17 UTC, chama1176 commented on sciurus17_examples_py/launch/example.launch.py
> +            '/config/sciurus17_moveit_py_examples.yaml').to_moveit_configs())
ありがとうございます。修正します
インデントや改行はyapfで今回フォーマットかけたのですが、何かの設定ファイルありますでしょうか？

2024-12-17 09:01 UTC, Kuwamai commented on sciurus17_examples_py/launch/example.launch.py
> +            '/config/sciurus17_moveit_py_examples.yaml').to_moveit_configs())
すみませんこちらは目で見たときのわかりやすさの話のため現状は設定ファイル等ないです。
設定する要素名が行頭にあるほうがわかりやすい程度の話になります。

2024-12-17 12:09 UTC, Kuwamai commented on sciurus17_examples_py/sciurus17_examples_py/gripper_control.py
> +    robot_model = sciurus17.get_robot_model()
承知いたしました。ではそのままで問題ないです。

2024-12-23 04:44 UTC, chama1176 commented
@Kuwamai レビュー指摘事項修正しましたので、再確認お願いします 😺

2024-12-23 11:29 UTC, Kuwamai requested changes
@chama1176 実機、シミュレータ両方で動作確認できました。パッケージ情報について少しコメントさせていただきましたのでご確認お願いします。

2024-12-23 11:29 UTC, Kuwamai commented on sciurus17_examples_py/package.xml
> +
authorタグはリリース時に更新されますか? 名前を追記いただければと思います。

2024-12-23 11:29 UTC, Kuwamai commented on sciurus17_examples_py/package.xml
> +  <description>python examples of Sciurus17 ROS package</description>
細かいですがこちらのPythonは大文字でいいかと思います。
```suggestion
  <description>Python examples of Sciurus17 ROS package</description>
```

2024-12-23 11:29 UTC, Kuwamai commented on sciurus17_examples_py/package.xml
> +  <version>0.1.0</version>
パッケージバージョンはリリース時に4.0.0になる認識で合っておりますでしょうか。

2024-12-24 01:50 UTC, chama1176 commented on sciurus17_examples_py/package.xml
> +  <version>0.1.0</version>
パッケージ単位だと新しいので0.1.0にしていましたが、他と合わせたほうが良さそうでしょうか？
少なくともリリース時は合わせたほうが良さそうですね

2024-12-24 02:01 UTC, chama1176 commented on sciurus17_examples_py/package.xml
> +
修正しました

2024-12-24 02:31 UTC, Kuwamai commented on sciurus17_examples_py/package.xml
> +  <version>0.1.0</version>
リリース前のバージョン表記に関しては短期間であればどちらでも大丈夫だと思います。
なので今回はリリース時に合えばいいと思います。
リリース時期が大幅に伸びてしまったり、バージョンを別々に管理したい場合は別リポジトリを作るのがよさそうですね。

2024-12-24 02:46 UTC, Kuwamai commented
@chama1176 あとすみません！こちらのREADMEが更新できていればOKだと思います :bow: 

> また、READMEのパッケージ一覧部分にsciurus17_examples_pyの記述を追加お願いします。
https://github.com/rt-net/sciurus17_ros/tree/ros2?tab=readme-ov-file#packages

2024-12-24 04:52 UTC, chama1176 commented
@Kuwamai 
コメント見逃してました。追加しました

2024-12-25 02:36 UTC, Kuwamai approved these changes
@chama1176 ありがとうございます。LGTMです！

2024-12-25 02:37 UTC, merged